<?php

/**
 * @file
 * Contains forum_plus.module.
 */

use Drupal\comment\Plugin\Field\FieldType\CommentItemInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function forum_plus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the forum_plus module.
    case 'help.page.forum_plus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Extends default forum functionality with some useful forum features.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements template_preprocess_forum_table_view_table().
 */
function template_preprocess_forum_plus_forum_table(&$variables) {
  template_preprocess_views_view_table($variables);
  // @todo: Make field configurable.
  $field_name = 'name';
  foreach ($variables['rows'] as $delta => &$row) {
    $row['columns'][$field_name]['depth'] = $variables['view']->result[$delta]->depth;
  }
}

// @todo: Introduce type.
function forum_plus_preprocess_forum_icon(&$variables) {
  $variables['hot_threshold'] = \Drupal::config('forum.settings')->get('topics.hot_threshold');

  if ($variables['num_posts'] > $variables['hot_threshold']) {
    $variables['icon_status'] = $variables['new_posts'] ? 'hot-new' : 'hot';
    $variables['icon_title'] = $variables['new_posts'] ? t('Hot topic, new comments') : t('Hot topic');
  }
  else {
    $variables['icon_status'] = $variables['new_posts'] ? 'new' : 'default';
    $variables['icon_title'] = $variables['new_posts'] ? t('New comments') : t('Normal topic');
    if ($variables['type'] == 'forum') {
      // @todo
      $variables['icon_title'] = $variables['new_posts'] ? t('New topics') : t('Normal topic');
    }
  }

  if ($variables['comment_mode'] == CommentItemInterface::CLOSED || $variables['comment_mode'] == CommentItemInterface::HIDDEN) {
    $variables['icon_status'] = 'closed';
    $variables['icon_title'] = t('Closed topic');
  }

  if ($variables['sticky'] == 1) {
    $variables['icon_status'] = 'sticky';
    $variables['icon_title'] = t('Sticky topic');
  }

  $variables['attributes']['title'] = $variables['icon_title'];
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function forum_plus_entity_view_mode_alter(&$view_mode, $entity, $context) {
  if (($view_mode == 'full' || $view_mode == 'default') && $entity->bundle() == 'forum') {
    $view_mode = 'topic_thread';
  }
}

/**
 * Implements hook_entity_insert().
 */
function forum_plus_entity_insert(EntityInterface $entity) {
  if (($entity->getEntityTypeId() == 'comment' && $entity->getTypeId() == 'comment_forum')
    || ($entity->getEntityTypeId() == 'node' && $entity->getType() == 'forum')) {

    // Increase post counter of user.
    $query = \Drupal::database()->update('forum_user_statistics')
      ->expression('post_count', 'post_count + 1')
      ->condition('uid', $entity->getOwnerId())
      ->execute();
  }
}
